name: first-workflow
on: [push]


jobs:
  shell-cmd-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo Hello3
        run: echo "Hello3 World"
      - name: multiple line cmd
        run: |
          node -v
          npm -v      