name: first-workflow
on: [push]

jobs:
  shell-cmd-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo Hello2
        run: echo "Hello2 World"
      - name: multiple line cmd
        run: |
          node -v
          npm -v      